Dungeons And Dragons Character Manager App/Models/Character.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Dungeons_And_Dragons_Character_Manager_App.Models
{
    public class Character
    {
        public int ID { get; set; }
        public string name { get; set; }
        public Race? Race { get; set; }
        public DndClass? CharacterClass { get; set; }
        public List<AbilityScore>? AbilityScores { get; set; }
        //public Background? Background { get; set; }
        public int currentHitPoints { get; set; }
        public int temporaryHitPoints { get; set; }
        public int maxHitPoints { get; set; }
        [NotMapped]
        public List<Item>? Equipment { get; set; }
        public int proficiencyBonus { get; set; }
        public int armourClass { get; set; }
        [ForeignKey("Skill")]
        public List<Skill>? Skills { get; set; }
        [NotMapped]
        public List<Item>? ItemProficiencies { get; set; }
        [ForeignKey("SkillProf")]
        public List<Skill>? SkillProficiencies { get; set; }
        public List<Ability>? SavingProficiencies { get; set; }
        public int currentHitDice { get; set; }
        public int totalHitDice { get; set; }
        [NotMapped]
        public List<string>? Languages { get; set; }
        public int numGold { get; set; }
        public int numSilver { get; set; }
        public int numCopper { get; set; }
        public int numPlatinum { get; set; }
        public int numElectrum { get; set; }

        [NotMapped]
        public List<int>? AsiOnLevel { get; set; }

        public Character(string name)
        {
            this.name = name;
        }

        public Character() { }

        public void ShortRest()
        {
            this.CharacterClass.ShortRest();
        }

        public void LongRest()
        {
            this.CharacterClass.LongRest();
        }

        public void LevelUp(Ability ability)
        {
            if (this.AsiOnLevel.Contains(this.CharacterClass.Level))
            {
                AbilityScore toUpdate = this.AbilityScores.First(score => score.Ability.Equals(ability));

                toUpdate.Score++;
                if (toUpdate.Score % 2 == 0)
                {
                    toUpdate.Modifier++;
                }
                
            }
            this.CharacterClass.LevelUp();
        }
        

        public int AbilityCheck(Ability ability)
        {
            Random random = new Random();
            int total;
            int rollResult = random.Next(1, 21);

            AbilityScore abilityScore = AbilityScores.First(score => score.Ability.Equals(ability));            
            int modifier = abilityScore.Modifier;
            
            total = modifier + rollResult;
            return total;
            
        }

        public int SkillCheck(Skill skill)
        {
            int total = AbilityCheck(skill.ParentAbility);

            if (SkillProficiencies.Any(proficiency => proficiency.Equals(skill)))
                total += proficiencyBonus;

            return total;
            
        }

        public int SavingThrow(Ability ability)
        {
            int total = AbilityCheck(ability);

            if (SavingProficiencies.Any(proficiency => proficiency.Equals(ability)))
                total += proficiencyBonus;

            return total;
        }

        public string CastSpell(Spell spell, int desiredLevel)
        {
            Wizard wizard = (Wizard)this.CharacterClass;
            var spellcast = spell.castSpell(wizard.SpellSlots, desiredLevel);
            wizard.SpellSlots = spellcast.Item1;
            return spellcast.Item2;
        }

        public string WeaponAttack(Weapon weapon, Ability ability)
        {
            int attack = AbilityCheck(ability);

            if (ItemProficiencies.Any(proficiency => ((Weapon)proficiency).Equals(weapon)))
            {
                attack += proficiencyBonus;
            }
            
            Random random = new Random();
            int damage = 0;
            foreach (var dice in weapon.DamageDice)
            {
                damage += random.Next(1, (int)dice);
            }

            string weaponAttack = $"Weapon: {weapon.Name} / Attack roll: {attack} / Damage roll: {damage}";

            return weaponAttack;
        }
    }
}

Dungeons And Dragons Character Manager App/Controllers/CharactersController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dungeons_And_Dragons_Character_Manager_App.Data;
using Dungeons_And_Dragons_Character_Manager_App.Models;

namespace Dungeons_And_Dragons_Character_Manager_App.Controllers
{
    public class CharactersController : Controller
    {
        private readonly CharacterManagerContext _context;

        public CharactersController(CharacterManagerContext context)
        {
            _context = context;
        }

        // GET: Characters
        public async Task<IActionResult> Index()
        {
            return View(await _context.Characters.ToListAsync());
        }

        // GET: Characters/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var character = await _context.Characters
                .FirstOrDefaultAsync(m => m.ID == id);
            if (character == null)
            {
                return NotFound();
            }

            return View(character);
        }

        // POST: Characters/CreateJSON
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult<Character>> CreateJSON([Bind("ID,name,currentHitPoints,temporaryHitPoints,maxHitPoints,proficiencyBonus,armourClass,currentHitDice,totalHitDice,numGold,numSilver,numCopper,numPlatinum,numElectrum")] Character character)
        {
            _context.Add(character);
            await _context.SaveChangesAsync();

            return CreatedAtAction(nameof(Index), new { id = character.ID }, character);
        }

        // GET: Characters/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Characters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,name,currentHitPoints,temporaryHitPoints,maxHitPoints,proficiencyBonus,armourClass,currentHitDice,totalHitDice,numGold,numSilver,numCopper,numPlatinum,numElectrum")] Character character)
        {
            if (ModelState.IsValid)
            {
                _context.Add(character);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(character);
        }

        // GET: Characters/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var character = await _context.Characters.FindAsync(id);
            if (character == null)
            {
                return NotFound();
            }
            return View(character);
        }

        // POST: Characters/AddClass/
        public async Task<IActionResult> AddClass(int id, [FromBody] string classname)
        {
            var character = await _context.Characters.FindAsync(id);
            if (ModelState.IsValid)
            {
                try
                {
                    if (classname.Equals("Fighter"))
                    {
                        character.CharacterClass = new Fighter();
                    }
                    else if (classname.Equals("Wizard"))
                    {
                        character.CharacterClass = new Wizard();
                    }
                    _context.Update(character);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CharacterExists(character.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return CreatedAtAction(nameof(Index), new { id = character.ID }, character);
        }

        // POST: Characters/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,name,playerName,currentHitPoints,temporaryHitPoints,maxHitPoints,proficiencyBonus,armourClass,experiencePoints,currentHitDice,totalHitDice,numGold,numSilver,numCopper,numPlatinum,numElectrum")] Character character)
        {
            if (id != character.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(character);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CharacterExists(character.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(character);
        }

        // GET: Characters/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var character = await _context.Characters
                .FirstOrDefaultAsync(m => m.ID == id);
            if (character == null)
            {
                return NotFound();
            }

            return View(character);
        }

        // POST: Characters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var character = await _context.Characters.FindAsync(id);
            _context.Characters.Remove(character);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CharacterExists(int id)
        {
            return _context.Characters.Any(e => e.ID == id);
        }
    }
}

Dungeons And Dragons Character Manager App/Views/Characters/Create.cshtml
@model Dungeons_And_Dragons_Character_Manager_App.Models.Character
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Dungeons_And_Dragons_Character_Manager_App

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Character</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="currentHitPoints" class="control-label"></label>
                <input asp-for="currentHitPoints" class="form-control" />
                <span asp-validation-for="currentHitPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="temporaryHitPoints" class="control-label"></label>
                <input asp-for="temporaryHitPoints" class="form-control" />
                <span asp-validation-for="temporaryHitPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="maxHitPoints" class="control-label"></label>
                <input asp-for="maxHitPoints" class="form-control" />
                <span asp-validation-for="maxHitPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="proficiencyBonus" class="control-label"></label>
                <input asp-for="proficiencyBonus" class="form-control" />
                <span asp-validation-for="proficiencyBonus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="armourClass" class="control-label"></label>
                <input asp-for="armourClass" class="form-control" />
                <span asp-validation-for="armourClass" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="currentHitDice" class="control-label"></label>
                <input asp-for="currentHitDice" class="form-control" />
                <span asp-validation-for="currentHitDice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="totalHitDice" class="control-label"></label>
                <input asp-for="totalHitDice" class="form-control" />
                <span asp-validation-for="totalHitDice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="numGold" class="control-label"></label>
                <input asp-for="numGold" class="form-control" />
                <span asp-validation-for="numGold" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="numSilver" class="control-label"></label>
                <input asp-for="numSilver" class="form-control" />
                <span asp-validation-for="numSilver" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="numCopper" class="control-label"></label>
                <input asp-for="numCopper" class="form-control" />
                <span asp-validation-for="numCopper" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="numPlatinum" class="control-label"></label>
                <input asp-for="numPlatinum" class="form-control" />
                <span asp-validation-for="numPlatinum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="numElectrum" class="control-label"></label>
                <input asp-for="numElectrum" class="form-control" />
                <span asp-validation-for="numElectrum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Dungeons And Dragons Character Manager App/Views/Characters/Delete.cshtml
@model Dungeons_And_Dragons_Character_Manager_App.Models.Character
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Dungeons_And_Dragons_Character_Manager_App
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Character</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.currentHitPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.currentHitPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.temporaryHitPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.temporaryHitPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.maxHitPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.maxHitPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.proficiencyBonus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.proficiencyBonus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.armourClass)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.armourClass)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.currentHitDice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.currentHitDice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.totalHitDice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.totalHitDice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.numGold)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.numGold)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.numSilver)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.numSilver)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.numCopper)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.numCopper)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.numPlatinum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.numPlatinum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.numElectrum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.numElectrum)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Dungeons And Dragons Character Manager App/Views/Characters/Details.cshtml
@model Dungeons_And_Dragons_Character_Manager_App.Models.Character
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Dungeons_And_Dragons_Character_Manager_App

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Character</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.currentHitPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.currentHitPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.temporaryHitPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.temporaryHitPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.maxHitPoints)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.maxHitPoints)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.proficiencyBonus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.proficiencyBonus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.armourClass)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.armourClass)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.currentHitDice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.currentHitDice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.totalHitDice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.totalHitDice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.numGold)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.numGold)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.numSilver)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.numSilver)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.numCopper)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.numCopper)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.numPlatinum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.numPlatinum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.numElectrum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.numElectrum)
        </dd>
    </dl>

    <dl class="row">
        @foreach (var item in Model.AbilityScores)
        {
            <dt class = "col-sm-2">
                 @Html.DisplayNameFor(modelItem => item.Ability.ToString())
            </dt>
            <dd class = "col-sm-10">
                @Html.DisplayFor(modelItem => item.Modifier)
            </dd>
        }
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Dungeons And Dragons Character Manager App/Views/Characters/Edit.cshtml
@model Dungeons_And_Dragons_Character_Manager_App.Models.Character
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Dungeons_And_Dragons_Character_Manager_App

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Character</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="currentHitPoints" class="control-label"></label>
                <input asp-for="currentHitPoints" class="form-control" />
                <span asp-validation-for="currentHitPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="temporaryHitPoints" class="control-label"></label>
                <input asp-for="temporaryHitPoints" class="form-control" />
                <span asp-validation-for="temporaryHitPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="maxHitPoints" class="control-label"></label>
                <input asp-for="maxHitPoints" class="form-control" />
                <span asp-validation-for="maxHitPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="proficiencyBonus" class="control-label"></label>
                <input asp-for="proficiencyBonus" class="form-control" />
                <span asp-validation-for="proficiencyBonus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="armourClass" class="control-label"></label>
                <input asp-for="armourClass" class="form-control" />
                <span asp-validation-for="armourClass" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="currentHitDice" class="control-label"></label>
                <input asp-for="currentHitDice" class="form-control" />
                <span asp-validation-for="currentHitDice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="totalHitDice" class="control-label"></label>
                <input asp-for="totalHitDice" class="form-control" />
                <span asp-validation-for="totalHitDice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="numGold" class="control-label"></label>
                <input asp-for="numGold" class="form-control" />
                <span asp-validation-for="numGold" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="numSilver" class="control-label"></label>
                <input asp-for="numSilver" class="form-control" />
                <span asp-validation-for="numSilver" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="numCopper" class="control-label"></label>
                <input asp-for="numCopper" class="form-control" />
                <span asp-validation-for="numCopper" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="numPlatinum" class="control-label"></label>
                <input asp-for="numPlatinum" class="form-control" />
                <span asp-validation-for="numPlatinum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="numElectrum" class="control-label"></label>
                <input asp-for="numElectrum" class="form-control" />
                <span asp-validation-for="numElectrum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Dungeons And Dragons Character Manager App/Views/Characters/Index.cshtml
@model IEnumerable<Dungeons_And_Dragons_Character_Manager_App.Models.Character>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, Dungeons_And_Dragons_Character_Manager_App

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-controller="Characters" asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.currentHitPoints)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.currentHitPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.temporaryHitPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.maxHitPoints)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.proficiencyBonus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.armourClass)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.currentHitDice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.totalHitDice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.numGold)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.numSilver)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.numCopper)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.numPlatinum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.numElectrum)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>